{
  "@type": "NewsArticle",
  "identifier": "2022--05--02--en--myfeed--HackerNews--NewsArticle--31239710",
  "url": "https://news.ycombinator.com/item?id=31239710",
  "headline": "PyPI Outage",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "bnert",
    "url": "https://news.ycombinator.com/user?id=bnert"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=31239710",
  "sameAs": "https://status.python.org",
  "dateCreated": "2022-05-02T20:10:11.783Z",
  "datePublished": "2022-05-02T19:30:39.000Z",
  "dateModified": "2022-05-02T20:10:11.783Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 2
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 0
    }
  ]
}