{
  "@type": "NewsArticle",
  "identifier": "2022--03--02--en--myfeed--HackerNews--NewsArticle--30533740",
  "url": "https://news.ycombinator.com/item?id=30533740",
  "headline": "Show HN: Rescue – type-safe exceptions for Python",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [
    "Show HN"
  ],
  "genre": "Show HN",
  "author": {
    "@type": "Person",
    "name": "idmitrievsky",
    "url": "https://news.ycombinator.com/user?id=idmitrievsky"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=30533740",
  "sameAs": "https://github.com/idmitrievsky/rescue",
  "dateCreated": "2022-03-02T22:10:47.782Z",
  "datePublished": "2022-03-02T21:55:03.000Z",
  "dateModified": "2022-03-02T22:10:47.782Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 1
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 0
    }
  ],
  "headline_zh-Hans": "Show HN: 拯救--Python的类型安全的异常",
  "headline_zh-Hant": "Show HN: 拯救--Python的類型安全的異常",
  "@context": [
    "https://schema.org",
    {
      "@vocab": "http://schema.org/",
      "@language": "en",
      "headline_zh-Hans": {
        "@id": "headline",
        "@language": "zh-Hans"
      },
      "headline_zh-Hant": {
        "@id": "headline",
        "@language": "zh-Hant"
      },
      "@version": 1.1
    }
  ]
}