{
  "@type": "NewsArticle",
  "identifier": "2022--06--19--en--myfeed--HackerNews--NewsArticle--31797557",
  "url": "https://news.ycombinator.com/item?id=31797557",
  "headline": "Tor network is under DDoS attack",
  "publisher": {
    "@type": "Organization",
    "name": "HackerNews",
    "url": "https://news.ycombinator.com",
    "logo": "https://hn.buzzing.cc/avatar.png"
  },
  "description": "",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "pcaversaccio",
    "url": "https://news.ycombinator.com/user?id=pcaversaccio"
  },
  "discussionUrl": "https://news.ycombinator.com/item?id=31797557",
  "sameAs": "https://status.torproject.org/",
  "dateCreated": "2022-06-19T10:26:42.876Z",
  "datePublished": "2022-06-19T08:59:49.000Z",
  "dateModified": "2022-06-19T10:26:42.876Z",
  "interactionStatistic": [
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "LikeAction"
      },
      "userInteractionCount": 2
    },
    {
      "@type": "InteractionCounter",
      "interactionType": {
        "@type": "CommentAction"
      },
      "userInteractionCount": 1
    }
  ],
  "headline_zh-Hans": "Tor网络受到DDoS攻击\n",
  "headline_zh-Hant": "Tor網絡受到DDoS攻擊\n",
  "@context": [
    "https://schema.org",
    {
      "@vocab": "http://schema.org/",
      "@language": "en",
      "headline_zh-Hans": {
        "@id": "headline",
        "@language": "zh-Hans"
      },
      "headline_zh-Hant": {
        "@id": "headline",
        "@language": "zh-Hant"
      },
      "@version": 1.1
    }
  ]
}