{
  "@type": "NewsArticle",
  "identifier": "2022--06--06--en--myfeed--rss--NewsArticle--c5fa5994ce92da85fc217ca8e02c63cb",
  "url": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "headline": "TPL and Error Handling & Continuation Tasks",
  "publisher": {
    "@type": "Organization",
    "name": "www.davidhaney.io",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "description": "Two of my colleagues (one from work and one from a user group) kindly pointed out to me that in my last post I omitted Continuation Tasksas a means of Error Handling for the TPL. As such, I will expand upon my last post with an example of handling errors via a Continuation Task.\nContinuing where we left off last, the following code will utilize a Task Continuation to handle errors within Tasks.",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "unknown",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "discussionUrl": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "sameAs": "https://www.davidhaney.io/tpl-and-error-handling-continuations/",
  "dateCreated": "2022-06-06T07:41:48.391Z",
  "datePublished": "2012-08-12T23:21:30.000Z",
  "dateModified": "2022-06-06T07:41:48.391Z",
  "interactionStatistic": []
}