{
  "@type": "NewsArticle",
  "identifier": "2022--03--09--en--myrss--rss--NewsArticle--9ef1347dc1ff726efdadc818524bf4da",
  "url": "https://www.davidhaney.io/tpl-and-error-handling/",
  "headline": "TPL and Error Handling",
  "publisher": {
    "@type": "Organization",
    "name": "www.davidhaney.io",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "description": "As of .NET 4.0, the TPL or Task Parallel Library is king when it comes to parallelization. It allows for smooth, easy multi-threading for any application. There is a slight learning curve, however, and a major part of this is understanding how Exceptions bubble-up while using the TPL.\nLetâ€™s partake in a simple example. This code will create and run a task that throws an Exception, and then attempt to catch it:",
  "keywords": [],
  "author": {
    "@type": "Person",
    "name": "unknown",
    "url": "https://www.davidhaney.io/index.xml"
  },
  "discussionUrl": "https://www.davidhaney.io/tpl-and-error-handling/",
  "sameAs": "https://www.davidhaney.io/tpl-and-error-handling/",
  "dateCreated": "2022-03-09T12:03:14.181Z",
  "datePublished": "2012-08-05T13:39:38.000Z",
  "dateModified": "2022-03-09T12:03:14.181Z",
  "interactionStatistic": []
}